import {BrowserRouter,Routes,Route} from "react-router-dom";
import {AuthProvider} from "./context/AuthContext";import {ThemeProvider} from "./context/ThemeContext";import {ChatProvider} from "./context/ChatContext";
import MainLayout from "./layouts/MainLayout";import ChatLayout from "./layouts/ChatLayout";import ProtectedRoute from "./components/ProtectedRoute";
import Home from "./pages/Home";import Login from "./pages/Login";import Register from "./pages/Register";import ForgotPassword from "./pages/ForgotPassword";import Chat from "./pages/Chat";import Search from "./pages/Search";import Research from "./pages/Research";import History from "./pages/History";import Files from "./pages/Files";import Profile from "./pages/Profile";import Settings from "./pages/Settings";import Privacy from "./pages/Privacy";import Terms from "./pages/Terms";import Contact from "./pages/Contact";
function Public({children}){return <MainLayout>{children}</MainLayout>}function Protected({children}){return <ProtectedRoute><MainLayout>{children}</MainLayout></ProtectedRoute>}function ChatProtected(){return <ProtectedRoute><ChatLayout><Chat/></ChatLayout></ProtectedRoute>}
export default function App(){return <BrowserRouter><Routes>
<Route path="/" element={<Public><Home/></Public>}/><Route path="/login" element={<Public><Login/></Public>}/><Route path="/register" element={<Public><Register/></Public>}/><Route path="/forgot-password" element={<Public><ForgotPassword/></Public>}/>
<Route path="/chat" element={<ChatProtected/>}/><Route path="/search" element={<Protected><Search/></Protected>}/><Route path="/research" element={<Protected><Research/></Protected>}/><Route path="/history" element={<Protected><History/></Protected>}/><Route path="/files" element={<Protected><Files/></Protected>}/><Route path="/profile" element={<Protected><Profile/></Protected>}/><Route path="/settings" element={<Protected><Settings/></Protected>}/><Route path="/privacy" element={<Public><Privacy/></Public>}/><Route path="/terms" element={<Public><Terms/></Public>}/><Route path="/contact" element={<Public><Contact/></Public>}/>
</Routes></BrowserRouter>}
